FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install numpy==1.21.0 joblib scikit-learn==1.3.0 pandas

# Comando para ejecutar el script de Python con argumentos
CMD ["python", "three_script.py"]