apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: UGFjaGFtYW1hMg==
  DB_NAME: bWluZF9ib29zdF9kYg==
  CLOUDINARY_CLOUD_NAME: ZHduaHI4YnVl
  CLOUDINARY_API_KEY: NDk4NjU5MzkxOTYzNTQz
  CLOUDINARY_API_SECRET: UkEwbTRkUGl3QkJOejRVRFlTNU1XRU1jdXY4