import { CiApple,
    CiAvocado,
    CiBasketball,
    CiBank,
    CiBeaker1,
    CiCalculator1,
    CiEdit,
    CiDatabase,
    CiDumbbell,
    CiGlobe,
    CiPen,
    CiServer,
    CiImageOn,
    CiMicrochip,
    CiPill,
    CiPickerHalf,
    CiStar} from 'react-icons/ci';

import { GiTomato } from "react-icons/gi";

export const ICON_NAMES = {
    Apple : CiApple,
    Avocado : CiAvocado,
    Basketball : CiBasketball,
    Bank : CiBank,
    SCIENCE: CiBeaker1,
    Calculator1: CiCalculator1,
    Edit: CiEdit,
    DATABASE: CiDatabase,
    Dumbbell:CiDumbbell,
    GLOBE: CiGlobe,
    PEN: CiPen,
    Star: CiStar,
    SERVER: CiServer,
    IMAGE: CiImageOn,
    Microchip:CiMicrochip,
    Pill:CiPill,
    PickerHalf:CiPickerHalf,
    Tomato: GiTomato
  };