
export const answersTree = {
    1: { id: 1, name: "Flash Card", type:"Metodo de estudio",  img: "/img/modes/Flashcard1.webp", description: "Designer" },
    2: { id: 2, name: "Rubber Duck", type:"Metodo de estudio",  img: "/img/modes/duck1.webp", description: "Developer" },
    3: { id: 3, name: "Rubber Duck Chat", type:"Metodo de estudio",  img: "/img/modes/duck1.webp", description: "Teacher" },
    4: { id: 4, name: "Analogia",  type:"Metodo de estudio", img: "/img/modes/comic1.webp", description: "Developer" },
    5: { id: 5, name: "Canva",  type:"Metodo de estudio", img: "/img/modes/canva1.webp", description: "Developer" },
    6: { id: 6, name: "Logro",  type:"Metodo de estudio", img: "/img/modes/trofeo1.webp", description: "Developer" },
    7: { id: 7, name: "Palacio de la memoria", type:"Metodo de estudio",  img: "/img/modes/mindpalace.webp", description: "Developer" },
    8: { id: 8, name: "Cronometro",  type:"Metodo de estudio", img: "/img/modes/flashreloj.webp", description: "Developer" },
    a: { id: 9, name: "Método Cornell", type:"Sistema de notas",  img: "/img/apuntes/cornell.webp", description: "Developer" },
    b: { id: 10, name: "Método Outline", type:"Sistema de notas",  img: "/img/apuntes/outline.webp", description: "Developer" },
    c: { id: 11, name: "Método Sentence", type:"Sistema de notas",  img: "/img/apuntes/oracion.webp", description: "Developer" },
    d: { id: 12, name: "Boxing", type:"Sistema de notas",  img: "/img/apuntes/box.webp", description: "Developer" },
    e: { id: 13, name: "Flow", type:"Sistema de notas",  img: "/img/apuntes/flow.webp", description: "Developer" },
    f: { id: 14, name: "Paginas Divididas", type:"Sistema de notas",  img: "/img/apuntes/dividida.webp", description: "Developer" },
    g: { id: 15, name: "Q/E/C", type:"Sistema de notas",  img: "/img/apuntes/quec.webp", description: "Developer" },
    h: { id: 16, name: "Método de Tablas", type:"Sistema de notas",  img: "/img/apuntes/tablas.webp", description: "Developer" },
    i: { id: 17, name: "Mapa Conceptual", type:"Sistema de notas",  img: "/img/apuntes/mapa.webp", description: "Developer" },
    option1: { id: 18, name: 'Eat the Frog', type:"Gestion de tiempo",  img: "/img/time/frog1.webp", description: "Dev"},
    option2: { id: 19, name: 'Time Blocking', type:"Gestion de tiempo",  img: "/img/time/block1.webp", description: "Dev"},
    option3: { id: 20, name: 'La matriz de Eisenhower', type:"Gestion de tiempo",  img: "/img/time/matriz1.webp", description: "Dev"},
    option4: { id: 21, name: 'Pomodoro',  type:"Gestion de tiempo", img: "/img/time/pomodoro1.webp", description: "Dev"},
    option5: { id: 22, name: 'Pomodoro',  type:"Gestion de tiempo", img: "/img/time/pomodoro1.webp", description: "Dev"},
    option6: { id: 23, name: 'Kanban',  type:"Gestion de tiempo", img: "/img/time/kanban1.webp", description: "Dev"},
    option7: { id: 24, name: 'GTD',  type:"Gestion de tiempo", img: "/img/time/gtd1.webp", description: "Dev"},
    option8: { id: 25, name: 'Pomodoro',  type:"Gestion de tiempo", img: "/img/time/pomodoro1.webp", description: "Dev"},
    option9: { id: 26, name: 'Invenario',  type:"Gestion de tiempo", img: "/img/time/inventario1.webp", description: "Dev"},
  }